language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository #Google Play Services
    - extra-android-m2repository #Design Support Library
    - extra-android-support
    - addon-google_apis-google-25
    - sys-img-armeabi-v7a-android-22

licenses:
  - 'android-sdk-license-.+'

before_install:
  - "chmod +x gradlew"
  - yes | sdkmanager "platforms;android-28"